version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "heroku local -f Procfile.dev"
    tty: true
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      ATM_DATABASE_PASSWORD: password
      ATM_DATABASE_USERNAME: postgres
      ATM_DATABASE_HOST: db
